"""New migration

Revision ID: b56008003ad7
Revises: 5bb19c7397b3
Create Date: 2025-05-21 23:24:19.546620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b56008003ad7'
down_revision: Union[str, None] = '5bb19c7397b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addons',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('Mod', 'ResourcePack', 'DataPack', 'Shader', 'Plugins', name='addontype'), nullable=False),
    sa.Column('short_description', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_addons_user_uuid_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_addons')),
    sa.UniqueConstraint('name', name=op.f('uq_addons_name'))
    )
    op.create_table('user_likes',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('addon_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addon_uuid'], ['addons.uuid'], name=op.f('fk_user_likes_addon_uuid_addons')),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_user_likes_user_uuid_users')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_user_likes')),
    sa.UniqueConstraint('user_uuid', 'addon_uuid', name='_user_addon_uc')
    )
    op.create_table('versions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('addon_uuid', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addon_uuid'], ['addons.uuid'], name=op.f('fk_versions_addon_uuid_addons')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_versions'))
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('versions')
    op.drop_table('user_likes')
    op.drop_table('addons')
    # ### end Alembic commands ###
